### ISSUE TITLE
startupScript fails silently

### ISSUE THREAD

**Issue by apowers313** [n-riesco/jp-kernel#11]
Startup scripts fail silently if they are broken and logging isn't enabled.

https://github.com/n-riesco/jp-kernel/blob/50dff2adaf69614f74814182805ef30827411017/lib/jp-kernel.js#L401

**Comment by n-riesco** [comment]
This is by design and it applies to all logging messages. To give you a little bit of background for this decision. A few years back Jupyter frontends would only accept `stream` messages to report writes to `stdout` and `stderr` from a kernel session. Users of some academic  libraries (e.g. tensorflow) wanted to see the writes these libraries made directly to `stdout` and `stderr`. The response of frontends was to report all writes to `stdout` and `stderr` as if they were `stream` messages; the unfortunate side-effect being the inclusion of kernel logging messages. For that reason I decided to hide logging messages behind a flag.
